### ISSUE TITLE
mlflow.exceptions.MlflowException

### ISSUE THREAD

**Issue by HongliXiao** [cogtoolslab/physics-benchmarking-neurips2021#60]
Hello, I encountered the following error when running the run.py of physics-models-master on the remote server, can you help me find out how to solve it?
This problem seems to be that the observed_readout_model.joblib file cannot be found, and I indeed did not find it in the corresponding folder.

…………………………
2023-09-04 20:28:37,770 [INFO] Found run with name: "pVGG_MLP-Collide-0-readout-Collide"

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
[A

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
2023-09-04 20:28:38,026 [ERROR] job exception: The following failures occurred while downloading one or more artifacts from /mnt/home/physion/physics-models-master/output_results/physopt-example/mlruns/0/30b1c1c66cc0460b9ff662586661572f/artifacts: {'readout_models/observed_readout_model.joblib': "FileNotFoundError(2, 'No such file or directory')"}

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    run()
  File "/mnt/home/physion/physopt-physics-benchmarking-main/physopt/opt.py", line 192, in run
    pipeline.run()
  File "/mnt/home/physion/physopt-physics-benchmarking-main/physopt/opt.py", line 100, in run
    run_once(data_space)
  File "/mnt/home/physion/physopt-physics-benchmarking-main/physopt/opt.py", line 91, in run_once
    run_inner(READOUT_PHASE_NAME, readout_space)
  File "/mnt/home/physion/physopt-physics-benchmarking-main/physopt/opt.py", line 74, in run_inner
    best = fmin(
  File "/usr/local/lib/python3.8/site-packages/hyperopt/fmin.py", line 507, in fmin
    return trials.fmin(
  File "/usr/local/lib/python3.8/site-packages/hyperopt/base.py", line 682, in fmin
    return fmin(
  File "/usr/local/lib/python3.8/site-packages/hyperopt/fmin.py", line 553, in fmin
    rval.exhaust()
  File "/usr/local/lib/python3.8/site-packages/hyperopt/fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/usr/local/lib/python3.8/site-packages/hyperopt/fmin.py", line 292, in run
    self.serial_evaluate()
  File "/usr/local/lib/python3.8/site-packages/hyperopt/fmin.py", line 170, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/usr/local/lib/python3.8/site-packages/hyperopt/base.py", line 907, in evaluate
    rval = self.fn(pyll_rval)
  File "/mnt/home/physion/physopt-physics-benchmarking-main/physopt/objective/core.py", line 109, in __call__
    ret = self.call(args)
  File "/mnt/home/physion/physics-models-master/physion/objective/objective.py", line 78, in call
    super().call(args)
  File "/mnt/home/physion/physopt-physics-benchmarking-main/physopt/objective/base.py", line 277, in call
    readout_model_file = utils.get_readout_model_from_artifact_store(protocol, self.tracking_uri, self.run_id, self.output_dir)
  File "/mnt/home/physion/physopt-physics-benchmarking-main/physopt/objective/utils.py", line 162, in get_readout_model_from_artifact_store
    readout_model_file = download_from_artifact_store(artifact_path, tracking_uri, run_id, output_dir)
  File "/mnt/home/physion/physopt-physics-benchmarking-main/physopt/objective/utils.py", line 128, in download_from_artifact_store
    client.download_artifacts(run_id, artifact_path, output_dir)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1809, in download_artifacts
    return self._tracking_client.download_artifacts(run_id, path, dst_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 492, in download_artifacts
    return self._get_artifact_repo(run_id).download_artifacts(path, dst_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 76, in download_artifacts
    return super().download_artifacts(artifact_path, dst_path)
  File "/usr/local/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repo.py", line 210, in download_artifacts
    raise MlflowException(
mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from /mnt/home/physion/physics-models-master/output_results/physopt-example/mlruns/0/30b1c1c66cc0460b9ff662586661572f/artifacts: {'readout_models/observed_readout_model.joblib': "FileNotFoundError(2, 'No such file or directory')"}

**Comment by HongliXiao** [comment]
OK:
mlflow==1.21.0
protobuf==3.20.0
tensorboardX==2.2
